import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageCircle, Route, ShieldCheck, CalendarDays } from "lucide-react";
const WA="https://wa.me/263780927394?text=Hello%20Uncle%20Lenny%2C%20our%20school%20would%20like%20to%20discuss%20transportation.";
export default function Schools(){
 return <main>
  <section className="page-hero"><div className="container"><p className="eyebrow red">FOR SCHOOLS</p><h1>Your school.<br/><span>Our transport team.</span></h1><p>A dependable transportation partner for daily school runs, trips and organised school travel.</p><a className="btn btn-red" href={WA} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Request a Quote</a></div></section>
  <section className="section"><div className="container split"><div><p className="eyebrow red">BUILT AROUND YOUR REQUIREMENTS</p><h2>Let&apos;s discuss your routes, timetable and student numbers.</h2><p>Every school has different requirements. Instead of forcing you into a fixed package, we can discuss the transport arrangement that makes sense for your school.</p><div className="check-list dark-text">{["Morning pickup routes","Afternoon drop-offs","School trips and excursions","Sports and extracurricular events","Dedicated or recurring vehicle arrangements"].map(x=><span key={x}><CheckCircle2 size={18}/>{x}</span>)}</div></div><div className="school-panel"><Route size={38}/><h3>What to include in your enquiry</h3><p>School name, pickup areas, destination, approximate number of students, required vehicles and timetable.</p></div></div></section>
  <section className="light-section"><div className="container"><div className="three-grid">{[[ShieldCheck,"Safety","Ask us about our driver, vehicle and operating procedures."],[CalendarDays,"Scheduling","Plan around your school&apos;s actual timetable."],[Route,"Routes","Discuss pickup points and practical route requirements."]].map(([Icon,title,text])=><div className="value-card" key={String(title)}><Icon size={27}/><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></div></section>
  <section className="cta"><div className="container cta-inner"><p className="eyebrow">SCHOOL PARTNERSHIPS</p><h2>Let&apos;s talk about your transport requirements.</h2><a className="btn btn-white" href={WA} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp our team</a></div></section>
 </main>
}
